// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prohuewhkiuuleqrdcju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByb2h1ZXdoa2l1dWxlcXJkY2p1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzODAwODQsImV4cCI6MjA2ODk1NjA4NH0.HGM0rkAeziyvj9PnD5oaymQC_vOrV0NiR5ANx3f99eo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});